name: CI Pipeline

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Compilar y ejecutar tests (JUnit + Cucumber)
        run: mvn clean install

      - name: Subir reportes de tests
        uses: actions/upload-artifact@v3
        with:
          name: reportes-tests
          path: target/surefire-reports
